### ISSUE TITLE
Relative path to source file

### ISSUE THREAD

**Issue by wleoncio** [stefan-m-lenz/JuliaConnectoR#20]
If I have some Julia functions stored in a module.jl file, this is what I do to import them in R:

```R
juliaCall("include", "/full/path/to/module.jl")
ju <- juliaImport(".myModule")
```

If this was part of a package, I know I could use `system.file()` to get the path to the module, but otherwise it's annoying (and unportable) to have to provide the full path to `juliaCall()`.

Is there another solution to passing the relative path to module.jl?

**Comment by stefan-m-lenz** [comment]
In R you can use the `normalizePath` function to get the full path of a file. If the module file is in your R project, you can simply write:

    juliaCall("include", normalizePath("module.jl"))

I would recommend this.

**Comment by wleoncio** [comment]
Thanks! I saw the usage of `normalizePath()` on [your paper](https://doi.org/10.18637/jss.v101.i06), but I ignored it since I assumed this function only served to replace "\\" with "/" on Windows path strings. Your code works as expected, cheers!
