### ISSUE TITLE
Mutlithreading through juliaConnectoR

### ISSUE THREAD

**Issue by bakaburg1** [stefan-m-lenz/JuliaConnectoR#7]
Hello! First of all many compliments for this package, it is quite well done!

I am a bit confused about how should juliaConnectoR be used to harness Julia multithreading capabilities. I understood that one needs to start Julia with the -t option to use multiple threads, but I wouldn't know how to do it through juliaConnectoR.

Many Thanks!

**Comment by stefan-m-lenz** [comment]
Thanks!

The number of threads in Julia can also be set via the `JULIA_NUM_THREADS` environment variable. 
The environment variable can be set also from R. It needs to be set before starting Julia:

```
> library(JuliaConnectoR)
> Sys.setenv(JULIA_NUM_THREADS = 6)
> juliaCall("Threads.nthreads")
Starting Julia ...
[1] 6
```

**Comment by bakaburg1** [comment]
Great, thanks!

Il giorno sab 5 giu 2021 alle ore 20:25 Stefan Lenz <
***@***.***> ha scritto:
